apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-scheduling-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-scheduling-service
  template:
    metadata:
      labels:
        app: appointment-scheduling-service
    spec:
      containers:
        - name: appointment-scheduling-service
          image: ranaliw/appointment-scheduling-service:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: healthsync-db-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-scheduling-service
spec:
  selector:
    app: appointment-scheduling-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
